-- Several columns were sized like short enum values (VARCHAR(64)) but actually
-- hold free-form descriptive text generated by the LLM (e.g. camera direction,
-- lighting mood, emotion, visual style) which easily exceeds that. Widen them
-- to unbounded TEXT. Columns that are genuinely app-controlled from a small
-- fixed set (camera_movement, transition_in, provider/asset/step type enums)
-- are left as-is.

ALTER TABLE scene ALTER COLUMN location TYPE TEXT;
ALTER TABLE scene ALTER COLUMN emotion TYPE TEXT;
ALTER TABLE scene ALTER COLUMN camera TYPE TEXT;
ALTER TABLE scene ALTER COLUMN lighting TYPE TEXT;
ALTER TABLE scene ALTER COLUMN visual_style TYPE TEXT;

ALTER TABLE episode ALTER COLUMN target_age TYPE TEXT;
ALTER TABLE episode ALTER COLUMN genre TYPE TEXT;
ALTER TABLE episode ALTER COLUMN tone TYPE TEXT;
ALTER TABLE episode ALTER COLUMN visual_style TYPE TEXT;
ALTER TABLE episode ALTER COLUMN language TYPE TEXT;

ALTER TABLE story_character ALTER COLUMN age TYPE TEXT;
