package com.aistorystudio.skit;
import org.springframework.core.io.FileSystemResource; import org.springframework.http.MediaType; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.nio.file.Path; import java.util.Map; import java.util.UUID;
@RestController @RequestMapping("/api/funny-skits")
public class FunnySkitController { private final FunnySkitService service; public FunnySkitController(FunnySkitService s){service=s;}
 @PostMapping("/jobs") public ResponseEntity<Map<String,UUID>> create(@RequestParam(value="character",required=false) MultipartFile character,@RequestParam("idea") String idea,@RequestParam("language") String language,@RequestParam(value="characterId",required=false) UUID characterId,@RequestParam(value="referenceId",required=false) UUID referenceId,@RequestParam(value="tone",required=false,defaultValue="absurd comedy") String tone,@RequestParam(value="speaker",required=false,defaultValue="Ira") String speaker,@RequestParam(value="style",required=false,defaultValue="realistic") String style){var j=service.createJob(character,idea,language,characterId,referenceId);j.setStyle(style);j.setIdea(idea);j.setTone(tone);service.generateAsync(j.getId(),idea,language,tone,speaker);return ResponseEntity.accepted().body(Map.of("jobId",j.getId()));}
 /** Edit one part (picture description and/or dialogue). */
 @PutMapping("/jobs/{id}/parts/{scene}") public ResponseEntity<Map<String,String>> updatePart(@PathVariable UUID id,@PathVariable int scene,@RequestBody Map<String,String> body){service.updatePart(id,scene,body.get("visualPrompt"),body.get("dialogue"));return ResponseEntity.ok(Map.of("status","ok"));}
 /** Same idea, character and style - a brand-new script and storyboard. */
 @PostMapping("/jobs/{id}/script/regenerate") public ResponseEntity<Map<String,String>> rewrite(@PathVariable UUID id,@RequestParam(value="speaker",required=false,defaultValue="Ira") String speaker,@RequestParam(value="style",required=false) String style){var j=service.job(id);if(style!=null)j.setStyle(style);service.rewriteScript(id,speaker);service.generateAsync(id,j.getIdea(),j.getLanguage(),j.getTone(),speaker);return ResponseEntity.accepted().body(Map.of("status","queued"));}
 @GetMapping("/jobs/{id}") public FunnySkitService.JobView status(@PathVariable UUID id){return service.status(id);}
 @PostMapping("/jobs/{id}/images/{scene}/regenerate") public ResponseEntity<Map<String,String>> regenerateImage(@PathVariable UUID id,@PathVariable int scene,@RequestParam(value="cascade",required=false,defaultValue="false") boolean cascade){service.regenerateImage(id,scene,cascade);return ResponseEntity.ok(Map.of("status","ok"));}
 @PostMapping("/jobs/{id}/render") public ResponseEntity<Map<String,String>> render(@PathVariable UUID id,@RequestParam(value="tone",required=false,defaultValue="viral reel comedy") String tone,@RequestParam(value="speaker",required=false,defaultValue="Ira") String speaker,@RequestParam(value="speechEngine",required=false,defaultValue="H3") String speechEngine){service.renderApprovedAsync(id,tone,speaker,speechEngine);return ResponseEntity.accepted().body(Map.of("status","started"));}
 @GetMapping("/jobs/{id}/images/{scene}") public ResponseEntity<FileSystemResource> image(@PathVariable UUID id,@PathVariable int scene){Path p=service.image(id,scene);return ResponseEntity.ok().contentType(MediaType.IMAGE_PNG).body(new FileSystemResource(p));}
 @GetMapping("/jobs/{id}/video") public ResponseEntity<FileSystemResource> video(@PathVariable UUID id){Path p=service.result(id);return ResponseEntity.ok().contentType(MediaType.parseMediaType("video/mp4")).body(new FileSystemResource(p));}
}
