package com.aistorystudio.domain.enums;

public enum JobStatus {
    QUEUED,
    ANALYZING,
    DRAFT_READY,
    WAITING_FOR_APPROVAL,
    APPROVED,
    GENERATING_SCENES,
    GENERATING_IMAGES,
    VALIDATING_IMAGES,
    GENERATING_AUDIO,
    ASSEMBLING_VIDEO,
    GENERATING_THUMBNAIL,
    GENERATING_SHORTS,
    QUALITY_CHECK,
    COMPLETED,
    FAILED,
    CANCELLED
}
