import {Component,OnDestroy,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {ApiService} from '../../services/api.service';
import {Project, Universe, Character, CharacterReference} from '../../models/models';
@Component({selector:'app-funny-skit',standalone:true,imports:[CommonModule,FormsModule],template:`
<header class="head"><div><span class="eyebrow">SHORT-FORM STUDIO</span><h1>Funny Skit Studio</h1><p class="muted">Create a standalone 15-second comedy clip in your selected Indian language. Use a saved Character Studio reference or upload a new temporary character.</p></div><span class="duration">15 sec</span></header>
<section class="grid"><div class="panel">
<div class="field"><label>Language</label><select [(ngModel)]="language"><option *ngFor="let l of languages" [value]="l">{{l}}</option></select></div>
<div class="field"><label>Character source</label><select [(ngModel)]="characterSource" (ngModelChange)="onCharacterSourceChange()"><option value="saved">Saved Character Studio character</option><option value="upload">Upload temporary character</option></select></div>
<div *ngIf="characterSource==='saved'" class="saved-character-box">
  <div class="picker-row"><div class="field"><label>Project</label><select [(ngModel)]="selectedProjectId" (ngModelChange)="onProjectChange()"><option value="">Choose project</option><option *ngFor="let p of projects" [value]="p.id">{{p.name}}</option></select></div>
  <div class="field"><label>Universe</label><select [(ngModel)]="selectedUniverseId" (ngModelChange)="onUniverseChange()" [disabled]="!selectedProjectId"><option value="">Choose universe</option><option *ngFor="let u of universes" [value]="u.id">{{u.name}}</option></select></div>
  <div class="field"><label>Character</label><select [(ngModel)]="selectedCharacterId" (ngModelChange)="onCharacterSelected()" [disabled]="!characters.length"><option value="">Choose saved character</option><option *ngFor="let c of characters" [value]="c.id">{{c.name}}</option></select></div></div>
  <div class="field" *ngIf="selectedCharacterId"><label>Saved reference</label><select [(ngModel)]="selectedReferenceId" (ngModelChange)="onReferenceSelected()" [disabled]="!references.length"><option value="">Choose saved reference</option><option *ngFor="let r of references" [value]="r.id">{{referenceLabel(r)}}</option></select></div>
  <div class="character" *ngIf="selectedReference as ref"><img [src]="api.characterReferenceImageUrl(ref.id)"><div><strong>🔒 {{ref.locked ? 'Locked master reference' : 'Saved reference'}}</strong><p class="muted">This DB-backed character reference will be used for storyboard images and all three H3 shots.</p></div></div>
  <p class="hint" *ngIf="selectedCharacterId && !references.length">No saved reference exists for this character. Generate one in Character Studio first.</p>
</div>
<div *ngIf="characterSource==='upload'" class="field"><label>Temporary main focus character</label><input type="file" accept="image/png,image/jpeg,image/webp" (change)="onCharacter($event)"><div class="character" *ngIf="preview"><img [src]="preview"><div><strong>{{locked?'🔒 Character locked':'Character reference'}}</strong><p class="muted">This upload is stored for this skit only. For reusable characters, generate/save a reference in Character Studio.</p><button type="button" class="btn" (click)="locked=!locked" [disabled]="!character">{{locked?'Unlock reference':'Lock character'}}</button></div></div></div>
<div class="field"><label>Funny skit idea</label><textarea rows="5" [(ngModel)]="idea" placeholder="Example: A village news reporter interviews a mischievous baby who confidently explains why he refuses to go to school."></textarea></div>
<div class="field"><label>Comedy style</label><select [(ngModel)]="tone"><option>absurd comedy</option><option>village comedy</option><option>news interview parody</option><option>family comedy</option><option>office comedy</option><option>deadpan comedy</option><option>viral reel comedy</option><option>satire</option></select></div>
<div class="fixed"><strong>15-second output</strong><span>Generated as 3 × 5-second H3 shots. Each part starts from the previous part’s final frame and keeps the selected saved reference or locked uploaded character.</span></div>
<button class="btn btn-primary" (click)="submit()" [disabled]="submitting||!canSubmit()">{{submitting?'Generating 15-sec skit...':'Generate funny skit'}}</button>
<p class="error" *ngIf="error">{{error}}</p></div>
<div class="panel result" *ngIf="job"><h2>Storyboard first</h2><p class="muted" *ngIf="job.status==='QUEUED'||job.status==='RUNNING'">Creating the script and three visual storyboards first. Review or regenerate any scene before video generation.</p><p class="error" *ngIf="job.status==='FAILED'">{{job.errorMessage}}</p><div class="storyboard" *ngIf="job.imageUrls"><div class="shot" *ngFor="let img of job.imageUrls; let i=index"><img *ngIf="img" [src]="img + '?v=' + imageVersion[i]"><div><strong>Part {{i+1}} · {{(i*5)}}–{{(i+1)*5}} sec</strong><p>{{job.dialogues?.[i]}}</p><button class="btn" type="button" (click)="regenerate(i+1)" [disabled]="regenerating[i]">{{regenerating[i]?'Regenerating...':'Regenerate image'}}</button></div></div></div><button class="btn btn-primary" *ngIf="job.status==='SUCCEEDED' && !resultUrl && allImagesReady()" (click)="render()" [disabled]="rendering">{{rendering?'Creating 3 × 5-sec videos...':'Looks good — create video'}}</button><div *ngIf="job.script" class="script"><strong>Script</strong><p>{{job.script}}</p></div><video *ngIf="resultUrl" [src]="resultUrl" controls autoplay loop></video><a *ngIf="resultUrl" class="btn" [href]="resultUrl" download>Download 15-sec skit</a></div></section>
`,styles:[`.head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start;margin-bottom:1.5rem}.eyebrow{font-size:.68rem;letter-spacing:.15em;color:var(--accent);font-weight:800}.head h1{margin:.35rem 0}.duration{border:1px solid var(--accent);border-radius:999px;padding:.55rem .9rem;color:var(--accent);font-weight:800}.grid{display:grid;grid-template-columns:minmax(0,760px) minmax(280px,1fr);gap:1.2rem}.panel{padding:1.2rem;border:1px solid var(--border);border-radius:16px;background:var(--surface);display:flex;flex-direction:column;gap:1rem}.field{display:flex;flex-direction:column;gap:.4rem}.picker-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.7rem}.saved-character-box{padding:.8rem;border:1px solid var(--border);border-radius:12px;background:rgba(255,255,255,.02)}.character{display:flex;gap:1rem;align-items:center;padding:.8rem;border:1px solid var(--border);border-radius:12px}.character img{width:150px;height:150px;object-fit:cover;border-radius:10px}.fixed{padding:.8rem;border:1px solid rgba(73,201,189,.35);border-radius:10px;background:rgba(73,201,189,.05)}.fixed span{display:block;color:var(--muted);font-size:.8rem;margin-top:.25rem}.storyboard{display:grid;gap:1rem}.shot{display:grid;grid-template-columns:180px 1fr;gap:1rem;padding:.8rem;border:1px solid var(--border);border-radius:12px}.shot img{width:180px;height:320px;object-fit:cover;border-radius:10px}.result video{width:100%;max-height:650px;border-radius:12px}.script{border-top:1px solid var(--border);padding-top:.8rem}.hint,.muted{color:var(--muted)}.error{color:var(--danger)}@media(max-width:900px){.grid{grid-template-columns:1fr}.picker-row{grid-template-columns:1fr}}` ]})
export class FunnySkitComponent implements OnDestroy,OnInit {
 languages=['Hindi','Kannada','Telugu','Tamil','Malayalam','Marathi','Bengali','Gujarati','Odia','Punjabi','Urdu','Assamese','Nepali','Sanskrit','Maithili','Manipuri','Bodo','Dogri','Konkani','Santali','Kashmiri','Indian English','Hinglish','English']; language='Kannada'; tone='news interview parody'; idea='A funny local-news style interview where the main character confidently says something completely unexpected.';
 characterSource:'saved'|'upload'='saved'; projects:Project[]=[]; universes:Universe[]=[]; characters:Character[]=[]; references:CharacterReference[]=[]; selectedProjectId=''; selectedUniverseId=''; selectedCharacterId=''; selectedReferenceId='';
 character?:File; preview=''; locked=false; submitting=false; error=''; job:any; resultUrl=''; private poll?:any; regenerating:boolean[]=[false,false,false]; imageVersion:number[]=[0,0,0]; rendering=false;
 constructor(public api:ApiService){}
 ngOnInit(){this.api.listProjects().subscribe({next:p=>this.projects=p,error:()=>{}})}
 get selectedReference():CharacterReference|undefined{return this.references.find(r=>r.id===this.selectedReferenceId)}
 onCharacterSourceChange(){this.error=''; if(this.characterSource==='saved'){this.character=undefined;this.locked=false;if(this.preview){URL.revokeObjectURL(this.preview);this.preview='';}}else{this.selectedCharacterId='';this.selectedReferenceId='';this.references=[];}}
 onProjectChange(){this.universes=[];this.characters=[];this.references=[];this.selectedUniverseId='';this.selectedCharacterId='';this.selectedReferenceId='';if(this.selectedProjectId)this.api.listUniverses(this.selectedProjectId).subscribe({next:u=>this.universes=u,error:()=>{}})}
 onUniverseChange(){this.characters=[];this.references=[];this.selectedCharacterId='';this.selectedReferenceId='';if(this.selectedUniverseId)this.api.listCharacters(this.selectedUniverseId).subscribe({next:c=>this.characters=c,error:()=>{}})}
 onCharacterSelected(){this.references=[];this.selectedReferenceId='';if(this.selectedCharacterId)this.api.listCharacterReferences(this.selectedCharacterId).subscribe({next:r=>{this.references=r||[];const preferred=this.references.find(x=>x.locked)||this.references.find(x=>x.primary)||this.references[0];if(preferred)this.selectedReferenceId=preferred.id;},error:()=>{this.references=[]}})}
 onReferenceSelected(){this.error=''}
 referenceLabel(r:CharacterReference){const state=r.locked?'locked':(r.primary?'primary':'saved');const when=r.createdAt?new Date(r.createdAt).toLocaleString():'';return `${state} · ${when}`}
 onCharacter(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;this.character=f;this.locked=false;if(this.preview)URL.revokeObjectURL(this.preview);this.preview=URL.createObjectURL(f);}
 canSubmit(){return !!this.idea.trim() && (this.characterSource==='saved'?!!this.selectedCharacterId&&!!this.selectedReferenceId:this.characterSource==='upload'&&!!this.character&&this.locked)}
 submit(){if(!this.canSubmit())return;this.submitting=true;this.error='';this.job=undefined;this.resultUrl='';this.api.createFunnySkitJob(this.characterSource==='upload'?(this.character??null):null,this.idea,this.language,this.tone,'Ira',this.characterSource==='saved'?this.selectedCharacterId:undefined,this.characterSource==='saved'?this.selectedReferenceId:undefined).subscribe({next:r=>{this.submitting=false;this.pollJob(r.jobId)},error:e=>{this.submitting=false;this.error=e?.error?.message||'Could not start the skit.'}})}
 regenerate(scene:number){if(!this.job)return;this.regenerating[scene-1]=true;this.api.regenerateFunnySkitImage(this.job.id,scene).subscribe({next:()=>{this.regenerating[scene-1]=false;this.imageVersion[scene-1]++;this.pollJobOnce(this.job.id)},error:e=>{this.regenerating[scene-1]=false;this.error=e?.error?.message||'Could not regenerate the image.'}})}
 allImagesReady(){return !!this.job?.imageUrls?.every((x:string|null)=>!!x)}
 render(){if(!this.job||!this.allImagesReady())return;this.rendering=true;this.api.renderFunnySkit(this.job.id,this.tone).subscribe({next:()=>{this.rendering=false;this.pollJob(this.job.id)},error:e=>{this.rendering=false;this.error=e?.error?.message||'Could not start video generation.'}})}
 pollJob(id:string){if(this.poll)clearInterval(this.poll);this.poll=setInterval(()=>this.pollJobOnce(id),4000);this.pollJobOnce(id)}
 pollJobOnce(id:string){this.api.getFunnySkitJob(id).subscribe({next:j=>{this.job=j;if(j.status==='FAILED'){if(this.poll)clearInterval(this.poll);this.poll=undefined;this.error=j.errorMessage||'Skit generation failed.'}else if(j.resultVideoPath){this.resultUrl=this.api.funnySkitResultUrl(id);this.rendering=false;if(this.poll)clearInterval(this.poll);this.poll=undefined;}},error:e=>{this.error=e?.error?.message||'Could not read skit status.'}})}
 ngOnDestroy(){if(this.poll)clearInterval(this.poll);if(this.preview)URL.revokeObjectURL(this.preview)}
}
