import {Component,OnDestroy} from '@angular/core';
import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {ApiService} from '../../services/api.service';
@Component({selector:'app-funny-skit',standalone:true,imports:[CommonModule,FormsModule],template:`
<header class="head"><div><span class="eyebrow">SHORT-FORM STUDIO</span><h1>Funny Skit Studio</h1><p class="muted">Create a standalone 15-second comedy clip in your selected Indian language. Upload one main character and lock the reference so H3 keeps the identity consistent across three continuous shots.</p></div><span class="duration">15 sec</span></header>
<section class="grid"><div class="panel">
<div class="field"><label>Language</label><select [(ngModel)]="language"><option *ngFor="let l of languages" [value]="l">{{l}}</option></select></div>
<div class="field"><label>Main focus character</label><input type="file" accept="image/png,image/jpeg,image/webp" (change)="onCharacter($event)"><div class="character" *ngIf="preview"><img [src]="preview"><div><strong>{{locked?'🔒 Character locked':'Character reference'}}</strong><p class="muted">{{locked?'This image will be used as the identity reference for all three 5-second parts.':'Upload a clear face/full-body reference, then lock it.'}}</p><button type="button" class="btn" (click)="locked=!locked" [disabled]="!character">{{locked?'Unlock reference':'Lock character'}}</button></div></div></div>
<div class="field"><label>Funny skit idea</label><textarea rows="5" [(ngModel)]="idea" placeholder="Example: A village news reporter interviews a mischievous baby who confidently explains why he refuses to go to school."></textarea></div>
<div class="field"><label>Comedy style</label><select [(ngModel)]="tone"><option>absurd comedy</option><option>village comedy</option><option>news interview parody</option><option>family comedy</option><option>office comedy</option><option>deadpan comedy</option><option>viral reel comedy</option><option>satire</option></select></div>
<div class="fixed"><strong>15-second output</strong><span>Generated as 3 × 5-second H3 shots. Each part starts from the previous part’s final frame and keeps the same locked character reference, then all three are merged into one 15-second video.</span></div>
<button class="btn btn-primary" (click)="submit()" [disabled]="submitting||!character||!idea.trim()||!locked">{{submitting?'Generating 15-sec skit...':'Generate funny skit'}}</button>
<p class="error" *ngIf="error">{{error}}</p></div>
<div class="panel result" *ngIf="job"><h2>Storyboard first</h2><p class="muted" *ngIf="job.status==='QUEUED'||job.status==='RUNNING'">Creating the script and three visual storyboards first. Review or regenerate any scene before video generation.</p><p class="error" *ngIf="job.status==='FAILED'">{{job.errorMessage}}</p><div class="storyboard" *ngIf="job.imageUrls"><div class="shot" *ngFor="let img of job.imageUrls; let i=index"><img *ngIf="img" [src]="img + '?v=' + imageVersion[i]"><div><strong>Part {{i+1}} · {{(i*5)}}–{{(i+1)*5}} sec</strong><p>{{job.dialogues?.[i]}}</p><button class="btn" type="button" (click)="regenerate(i+1)" [disabled]="regenerating[i]">{{regenerating[i]?'Regenerating...':'Regenerate image'}}</button></div></div></div><button class="btn btn-primary" *ngIf="job.status==='SUCCEEDED' && !resultUrl && allImagesReady()" (click)="render()" [disabled]="rendering">{{rendering?'Creating 3 × 5-sec videos...':'Looks good — create video'}}</button><div *ngIf="job.script" class="script"><strong>Script</strong><p>{{job.script}}</p></div><video *ngIf="resultUrl" [src]="resultUrl" controls autoplay loop></video><a *ngIf="resultUrl" class="btn" [href]="resultUrl" download>Download 15-sec skit</a></div></section>
`,styles:[`.head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start;margin-bottom:1.5rem}.eyebrow{font-size:.68rem;letter-spacing:.15em;color:var(--accent);font-weight:800}.head h1{margin:.35rem 0}.duration{border:1px solid var(--accent);border-radius:999px;padding:.55rem .9rem;color:var(--accent);font-weight:800}.grid{display:grid;grid-template-columns:minmax(0,760px) minmax(280px,1fr);gap:1.2rem}.panel{padding:1.2rem;border:1px solid var(--border);border-radius:16px;background:var(--surface);display:flex;flex-direction:column;gap:1rem}.field{display:flex;flex-direction:column;gap:.4rem}.character{display:flex;gap:1rem;align-items:center;padding:.8rem;border:1px solid var(--border);border-radius:12px}.character img{width:150px;height:150px;object-fit:cover;border-radius:10px}.fixed{padding:.8rem;border:1px solid rgba(73,201,189,.35);border-radius:10px;background:rgba(73,201,189,.05)}.fixed span{display:block;color:var(--muted);font-size:.8rem;margin-top:.25rem}.storyboard{display:grid;gap:1rem}.shot{display:grid;grid-template-columns:180px 1fr;gap:1rem;padding:.8rem;border:1px solid var(--border);border-radius:12px}.shot img{width:180px;height:320px;object-fit:cover;border-radius:10px}.result video{width:100%;max-height:650px;border-radius:12px}.script{border-top:1px solid var(--border);padding-top:.8rem}.error{color:var(--danger)}@media(max-width:900px){.grid{grid-template-columns:1fr}}` ]})
export class FunnySkitComponent implements OnDestroy {
 languages=['Hindi','Kannada','Telugu','Tamil','Malayalam','Marathi','Bengali','Gujarati','Odia','Punjabi','Urdu','Assamese','Nepali','Sanskrit','Maithili','Manipuri','Bodo','Dogri','Konkani','Santali','Kashmiri','Indian English','Hinglish','English']; language='Kannada'; tone='news interview parody'; idea='A funny local-news style interview where the main character confidently says something completely unexpected.'; character?:File; preview=''; locked=false; submitting=false; error=''; job:any; resultUrl=''; private poll?:any; regenerating:boolean[]=[false,false,false]; imageVersion:number[]=[0,0,0]; rendering=false;
 constructor(private api:ApiService){}
 onCharacter(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;this.character=f;this.locked=false;if(this.preview)URL.revokeObjectURL(this.preview);this.preview=URL.createObjectURL(f);}
 submit(){if(!this.character||!this.locked||!this.idea.trim())return;this.submitting=true;this.error='';this.job=undefined;this.resultUrl='';this.api.createFunnySkitJob(this.character,this.idea,this.language,this.tone).subscribe({next:r=>{this.submitting=false;this.pollJob(r.jobId)},error:e=>{this.submitting=false;this.error=e?.error?.message||'Could not start the skit.'}})}
 regenerate(scene:number){if(!this.job)return;this.regenerating[scene-1]=true;this.api.regenerateFunnySkitImage(this.job.id,scene).subscribe({next:()=>{this.regenerating[scene-1]=false;this.imageVersion[scene-1]++;this.pollJobOnce(this.job.id)},error:e=>{this.regenerating[scene-1]=false;this.error=e?.error?.message||'Could not regenerate the image.'}})}
 allImagesReady(){return !!this.job?.imageUrls?.every((x:string|null)=>!!x)}
 render(){if(!this.job||!this.allImagesReady())return;this.rendering=true;this.api.renderFunnySkit(this.job.id,this.tone).subscribe({next:()=>{this.rendering=false;this.pollJob(this.job.id)},error:e=>{this.rendering=false;this.error=e?.error?.message||'Could not start video generation.'}})}
 pollJob(id:string){if(this.poll)clearInterval(this.poll);this.poll=setInterval(()=>this.pollJobOnce(id),4000);this.pollJobOnce(id)}
 pollJobOnce(id:string){this.api.getFunnySkitJob(id).subscribe({next:j=>{this.job=j;if(j.status==='FAILED'){if(this.poll)clearInterval(this.poll);this.poll=undefined;this.error=j.errorMessage||'Skit generation failed.'} else if(j.resultVideoPath){this.resultUrl=this.api.funnySkitResultUrl(id);this.rendering=false;if(this.poll)clearInterval(this.poll);this.poll=undefined;}},error:e=>{this.error=e?.error?.message||'Could not read skit status.'}})}
 ngOnDestroy(){if(this.poll)clearInterval(this.poll);if(this.preview)URL.revokeObjectURL(this.preview)}
}
